name: Gestao de vagas Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t loyanemenezes/gestao_vagas .

      - name: Publish image
        run: docker push loyanemenezes/gestao_vagas

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image docker Hub
        run: docker pull loyanemenezes/gestao_vagas:latest

      - name: remove container
        run: docker rm -f gestao-vagas || true

      - name: Run docker container gestao-vagas
        run: |
          docker run -d \
            -p 8080:8080 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
            -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
            loyanemenezes/gestao_vagas:latest
